# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/fzwwj95/work/Learn/FPGA/qi/04_uart/uart.srcs/sources_1/ip/UART_FIFO/UART_FIFO.xci
# IP: The module: 'UART_FIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fzwwj95/work/Learn/FPGA/qi/04_uart/uart.gen/sources_1/ip/UART_FIFO/UART_FIFO.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_FIFO'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/fzwwj95/work/Learn/FPGA/qi/04_uart/uart.gen/sources_1/ip/UART_FIFO/UART_FIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/fzwwj95/work/Learn/FPGA/qi/04_uart/uart.srcs/sources_1/ip/UART_FIFO/UART_FIFO.xci
# IP: The module: 'UART_FIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fzwwj95/work/Learn/FPGA/qi/04_uart/uart.gen/sources_1/ip/UART_FIFO/UART_FIFO.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/fzwwj95/work/Learn/FPGA/qi/04_uart/uart.gen/sources_1/ip/UART_FIFO/UART_FIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
