# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/fzwwj95/work/Learn/FPGA/qi/04_uart/uart.srcs/sources_1/ip/system_pll/system_pll.xci
# IP: The module: 'system_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fzwwj95/work/Learn/FPGA/qi/04_uart/uart.gen/sources_1/ip/system_pll/system_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_pll'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/fzwwj95/work/Learn/FPGA/qi/04_uart/uart.gen/sources_1/ip/system_pll/system_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/fzwwj95/work/Learn/FPGA/qi/04_uart/uart.gen/sources_1/ip/system_pll/system_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/fzwwj95/work/Learn/FPGA/qi/04_uart/uart.srcs/sources_1/ip/system_pll/system_pll.xci
# IP: The module: 'system_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fzwwj95/work/Learn/FPGA/qi/04_uart/uart.gen/sources_1/ip/system_pll/system_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/fzwwj95/work/Learn/FPGA/qi/04_uart/uart.gen/sources_1/ip/system_pll/system_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/fzwwj95/work/Learn/FPGA/qi/04_uart/uart.gen/sources_1/ip/system_pll/system_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
